version: '3'

services:
  mjpg-streamer:
    container_name: mjpg-streamer
    image: berardinux-mjpg-streamer:latest
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 80:8080
    command: ["./mjpg_streamer", "-i", "input_uvc.so -y -d /dev/video0 -r 1920x1080 -f 30", "-o", "output_http.so -w ./www"]
    privileged: true
