version: '3'

services:
  mjpg-streamer:
    container_name: mjpg-streamer
    image: kvaps/mjpg-streamer
    command: -i "/usr/lib64/input_uvc.so -y -d /dev/video0 -r 1920x1080 -f 30" -o "/usr/lib64/output_http.so -p 8080 -w /usr/share/mjpeg-streamer/www/"
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 10000:8080
